Facturacion/Controllers/DetalleFacturaController.cs
using Business.Areas.DetalleFactura;
using Business.Areas.Producto;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Facturacion.Controllers
{
    public class DetalleFacturaController : Controller
    {
        // GET: DetalleFactura
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(int id)
        {
            ProductoBusiness business = new ProductoBusiness();
            List<ProductoDTO> clientes = new List<ProductoDTO>();
            clientes = business.GetListProducto();
            List<SelectListItem> lst = new List<SelectListItem>();

            foreach (var item in clientes)
            {
                SelectListItem select = new SelectListItem();
                select.Text = item.Nombre;
                select.Value = item.Id_Producto.ToString();
                lst.Add(select);
            }
            ViewBag.Opciones = lst;
            DetalleFacturaDTO detalleFacturaDTO = new DetalleFacturaDTO();
            detalleFacturaDTO.Fk_Factura = id;
            return View(detalleFacturaDTO);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DetalleFacturaDTO detallleFacturaDTO)
        {
            DetalleFacturaDTO factura = new DetalleFacturaDTO();
            try
            {
                DetalleFacturaBusiness facturaBusiness = new DetalleFacturaBusiness();
                factura = facturaBusiness.CreateDetalleFactura(detallleFacturaDTO);


            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return Redirect("~/Factura/");
        }
    }
}

Facturacion/Views/DetalleFactura/Create.cshtml
@model Business.Areas.DetalleFactura.DetalleFacturaDTO

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>


@using (Html.BeginForm("Create", "DetalleFactura", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Cliente</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.Fk_Factura)
    <div class="form-group">
        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fk_Producto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(x => x.Fk_Producto, (IEnumerable<SelectListItem>)ViewBag.Opciones, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Fk_Producto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}