Facturacion/Controllers/ProductoController.cs
using Business.Areas.Producto;
using Facturacion.Controllers.ServiciosWebApi;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Facturacion.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {
            ProductoAPI productoBusiness = new ProductoAPI();
            var list = productoBusiness.GetListProducto();

            return View(list);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductoDTO productoDTO)
        {
            ProductoDTO producto = new ProductoDTO();
            try
            {
                ProductoBusiness productoBusiness = new ProductoBusiness();
                producto = productoBusiness.CreateProducto(productoDTO);
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Ocurrio un error en el sistema, comuniquese con el administrador");
            }
            return Redirect("~/Producto/");
        }

        public ActionResult Update(int Id)
        {
            ProductoDTO producto = new ProductoDTO();
            ProductoBusiness productoBusiness = new ProductoBusiness();
            producto = productoBusiness.GetProdutoById(Id);

            return View(producto);
        }

        [HttpPost]
        public ActionResult Update(ProductoDTO productoDTO)
        {
            ProductoDTO producto = new ProductoDTO();
            try
            {
                ProductoBusiness productoBusiness = new ProductoBusiness();
                producto = productoBusiness.UpdateProducto(productoDTO);
            }
            catch (DataException dex)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Ocurrio un error, no se actualizo el producto");
            }
            return Redirect("~/Producto/");
        }

        //Eliminar cliente
        public ActionResult Delete(int Id)
        {
            ProductoBusiness productoBusiness = new ProductoBusiness();
            int IdProducto = productoBusiness.DeleteProducto(Id);

            return Redirect("~/Producto/");
        }

        public ActionResult ConsultaProductosExistencia()
        {
            ProductoBusiness productoBusiness = new ProductoBusiness();
            var list = productoBusiness.GetListProductoByExist();

            return View(list);
        }

        public ActionResult ProductosVendidos()
        {
            ProductoAPI productoBusiness = new ProductoAPI();
            var list = productoBusiness.GetListProductosVendidos();

            return View(list);
        }

    }
}

Facturacion/Views/Producto/ConsultaProductosExistencia.cshtml
@model IEnumerable<Business.Areas.Producto.ProductoDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Lista Productos Existencia</h2>

<p>
    <a class="btn btn-primary" href="~/Producto/Create">Nuevo Producto</a>

</p>
<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Nombre
        </th>
        <th>
            Descripcion
        </th>
        <th>
            Precio
        </th>
        <th>
            Stock
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id_Producto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stock)
            </td>
            <td>
                <a class="btn btn-default" href="~/Producto/Update/@item.Id_Producto">Editar</a>
                <a class="btn btn-danger" href="~/Producto/Delete/@item.Id_Producto">Eliminar</a>
            </td>
        </tr>
    }

</table>

Facturacion/Views/Producto/Create.cshtml
@model Business.Areas.Producto.ProductoDTO

@{
    ViewBag.Title = "Crear Productos";
}

<h2>Crear Productos</h2>


@using (Html.BeginForm("Create", "Producto", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista Productos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Facturacion/Views/Producto/Index.cshtml
@model IEnumerable<Business.Areas.Producto.ProductoDTO>

@{
    ViewBag.Title = "Index";
}

<h2>Productos</h2>

<p>
    <a class="btn btn-primary" href="~/Producto/Create">Nuevo Producto</a>

</p>

<p>
    <a class="btn btn-primary" href="~/Producto/ConsultaProductosExistencia">Lista Productos Existencia</a>

</p>
<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Nombre
        </th>
        <th>
            Descripcion
        </th>
        <th>
            Precio
        </th>
        <th>
            Stock
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id_Producto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stock)
            </td>
            <td>
                <a class="btn btn-default" href="~/Producto/Update/@item.Id_Producto">Editar</a>
                <a class="btn btn-danger" href="~/Producto/Delete/@item.Id_Producto">Eliminar</a>
            </td>
        </tr>
    }

</table>

Facturacion/Views/Producto/ProductosVendidos.cshtml
@model IEnumerable<Business.Areas.Producto.FacturaDetalleProducto>

@{
    ViewBag.Title = "Index";
}

<h2>Productos Vendidos</h2>

<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Nombre
        </th>
        <th>
            Precio
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id_Producto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                <a class="btn btn-default" href="~/Producto/Update/@item.Id_Producto">Editar</a>
                <a class="btn btn-danger" href="~/Producto/Delete/@item.Id_Producto">Eliminar</a>
            </td>
        </tr>
    }

</table>

Facturacion/Views/Producto/Update.cshtml
@model Business.Areas.Producto.ProductoDTO

@{
    ViewBag.Title = "Update";
}

<h2>Editar Producto</h2>


@using (Html.BeginForm("Update", "Producto", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ClienteDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_Producto)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Lista Productos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}